DATASET:
  base_path: /home/yashturkar/Downloads/sequence-samples/lab2113-v2_seq001_20260813_013825_386126/vslamlab
  name: lab2113-v2_seq001
  baseline: orbslam2
  dataset: lightning
  sensor_type: stereo
  groundtruth_format: kitti
  output_dir: output/orbslam2_stereo

EVALUATION:
  max_time_difference_s: 0.02
  fast_lio:
    enabled: true
    workspace: /home/yashturkar/humble_ws
