DATASET:
  base_path: /mnt/share/nas/tmp/lightning_vslam/vslam_3nlbqi47
  name: sequence_31bc827d
  baseline: vggtslam
  groundtruth_format: kitti
  output_dir: output
  sensor_type: mono
  dataset: /home/kraken/Workspace/VSLAM-LAB/Datasets/dataset_files/dataset_lightning.py
